### ISSUE TITLE
Wikipedia description in other languages

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-Wikidata#82]
We do not display the Wikipedia description for these requests in Spanish (the Wikipedia pages do exist): [(Francia,capital,?)](http://askplatyp.us/?lang=es&q=(Francia%2Ccapital%2C%3F)), [(Alemania,capital,?)](http://askplatyp.us/?lang=es&q=(Alemania%2Ccapital%2C%3F)).

Same problem in Italian: [(Francia,capital,?)](http://askplatyp.us/?lang=it&q=(Francia%2Ccapital%2C%3F)), [(Francia,capo di Stato,?)](http://askplatyp.us/?lang=it&q=(Francia%2Ccapo+di+Stato%2C%3F)).

It seems to work well in French.

PS: how do you succesfully retrieve the entities in other languages? For example, the [France](http://www.wikidata.org/wiki/Q142) entity is not translated in Spanish, but requests about "Francia" work.

**Comment by Tpt** [comment]
Yes, it is because I haven't configured the module yet to support Italian and Spanish Wikipedias. See https://github.com/ProjetPP/PPP-Wikidata/blob/master/www/index.php


>PS: how do you successfully retrieve the entities in other languages? For example, the France entity is not translated in Spanish, but requests about "Francia" work.

Q142 has label in more than 50 languages. But all the labels are not displayed by default. To see/edit them you should use the gadget "label lister" (it can be activated in Preferences/Gadgets).

**Comment by Ezibenroc** [comment]
Ok, thank you.
Would be good to allow all the Wikidata languages (or at least the most spoken ones, such as Chinese, Arabic, Spanish, Portuguese and German, in addition of English and French).

**Comment by Tpt** [comment]
"all the Wikidata languages": Wikidata supports more languages than there are of Wikipedias.

+1 for this list.
